-- Actualiza supervision.supervisor_sebin desde campamentos_damnificados_2026-07-06.json
-- Aplicado vía MCP execute_sql el 06-jul-2026.

UPDATE centros c
SET
  updated_at = (extract(epoch from now()) * 1000)::bigint,
  updated_by = 'admin',
  data = jsonb_set(
    COALESCE(c.data, '{}'::jsonb),
    '{supervision}',
    COALESCE(c.data->'supervision', '{}'::jsonb) || jsonb_build_object('supervisor_sebin', m.superv_sebin),
    true
  )
FROM (VALUES
  ('centro-09', 'C/M GUZMÁN BORNIA'),
  ('centro-10', 'C/M GUZMÁN BORNIA'),
  ('centro-37', 'C/J HÉCTOR GODOY'),
  ('centro-36', 'C/J HÉCTOR GODOY'),
  ('centro-34', 'C/J HÉCTOR GODOY'),
  ('centro-53', 'C/J HÉCTOR GODOY'),
  ('centro-05', 'C/G RONNY GALDONAS'),
  ('centro-04', 'C/G RONNY GALDONAS'),
  ('centro-03', 'C/G RONNY GALDONAS'),
  ('centro-51', 'C/G RONNY GALDONAS'),
  ('centro-52', 'C/G RONNY GALDONAS'),
  ('centro-54', 'C/G RONNY GALDONAS'),
  ('centro-30', 'C/G PÉREZ LÓPEZ'),
  ('centro-28', 'C/J PÉREZ LÓPEZ'),
  ('centro-26', 'C/J PÉREZ LÓPEZ'),
  ('centro-29', 'C/J PÉREZ LÓPEZ'),
  ('centro-27', 'C/J PÉREZ LÓPEZ'),
  ('centro-55', 'C/J PÉREZ LÓPEZ'),
  ('centro-11', 'C/G ROZO'),
  ('centro-02', 'C/G ROZO'),
  ('centro-01', 'C/G ROZO'),
  ('centro-25', 'C/M CARDOZO'),
  ('centro-24', 'C/M CARDOZO'),
  ('centro-23', 'C/M YOHANA CARDOZO'),
  ('centro-56', 'C/M YOHANA CARDOZO'),
  ('centro-57', 'C/M ELIS FERNANDEZ'),
  ('centro-58', 'C/M ELIS FERNANDEZ'),
  ('centro-16', 'C/G RAMÓN YÉPEZ'),
  ('centro-17', 'C/G RAMÓN YÉPEZ'),
  ('centro-18', 'C/G RAMÓN YÉPEZ'),
  ('centro-19', 'C/G RAMÓN YÉPEZ'),
  ('centro-59', 'C/G SHIRLEY'),
  ('centro-21', 'C/G NOVO'),
  ('centro-20', 'C/G NOVO'),
  ('centro-60', 'C/G NOVO'),
  ('centro-46', 'C/G JOSÉ MARTÍNEZ'),
  ('centro-48', 'C/G JOSÉ MARTÍNEZ'),
  ('centro-49', 'C/G JOSÉ MARTÍNEZ'),
  ('centro-61', 'C/G JOSÉ MARTÍNEZ'),
  ('centro-31', 'C/G CARLOS ORTEGA'),
  ('centro-32', 'C/G CARLOS ORTEGA'),
  ('centro-33', 'C/G CARLOS ORTEGA'),
  ('centro-62', 'C/G CARLOS ORTEGA'),
  ('centro-63', 'C/G CARLOS ORTEGA'),
  ('centro-06', 'C/G LUIS MARRÓN'),
  ('centro-08', 'C/G LUIS MARRÓN'),
  ('centro-50', 'C/G BRITO'),
  ('centro-12', 'C/M CARLOS GAMBOA'),
  ('centro-41', 'C/G CARLOS CONTRERAS'),
  ('centro-38', 'C/G CARLOS CONTRERAS'),
  ('centro-40', 'C/G CARLOS CONTRERAS'),
  ('centro-39', 'C/G CARLOS CONTRERAS'),
  ('centro-64', 'C/G MAIKENFER'),
  ('centro-14', 'C/M AGUANA'),
  ('centro-13', 'C/M AGUANA'),
  ('centro-45', 'C/G YIMMY BETANCOURT'),
  ('centro-43', 'C/G YIMMY BETANCOURT'),
  ('centro-44', 'C/G YIMMY BETANCOURT'),
  ('centro-42', 'C/G YIMMY BETANCOURT'),
  ('centro-65', 'C/G YIMMY BETANCOURT'),
  ('centro-66', 'C/G NOGUERA')
) AS m(centro_id, superv_sebin)
WHERE c.id = m.centro_id
  AND c.deleted = false;
