-- =============================================================================
-- Traslado nominal entre campamentos desde el censo por cédula (referencia).
--
-- La versión vigente (motivo obligatorio, insert en `traslados` con
-- fuente='censo_nominal', bitácora por refugiado) vive en:
--   supabase/traslados_historial_unificado.sql
--
-- Firma: trasladar_nominal_a_centro(p_cedula_norm, p_centro_id, p_modo, p_motivo)
-- =============================================================================
